"""
Simulator - Simple Code Execution Node
======================================
Executes the Python code generated by the Scientist.
Returns success/failure and conductivity/error message.
Does NOT attempt to debug or fix code.
"""

import sys
import subprocess
import time
from typing import Dict, Any

from kokoa.state import AgentState, SimulationResult
from kokoa.config import Config


def execute_simulation(code: str, file_path: str = "", timeout: int = Config.TIMEOUT) -> SimulationResult:
    """
    Execute KMC simulation code with timeout using subprocess.run
    Uses file-based communication instead of multiprocessing.Queue
    """
    import os
    
    if not file_path:
        return SimulationResult(
            is_success=False,
            conductivity=0.0,
            error_message="No file path provided for simulation",
            execution_log="No file path"
        )
    
    try:
        # Run the saved Python file as a subprocess
        result = subprocess.run(
            [sys.executable, file_path],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=os.path.dirname(file_path)
        )
        
        output = result.stdout
        stderr = result.stderr
        
        if result.returncode != 0:
            error_msg = stderr if stderr else f"Process exited with code {result.returncode}"
            return SimulationResult(
                is_success=False,
                conductivity=0.0,
                error_message=error_msg,
                execution_log=output + "\n" + stderr
            )
        
    except subprocess.TimeoutExpired:
        return SimulationResult(
            is_success=False,
            conductivity=0.0,
            error_message=f"Timeout: Simulation took longer than {timeout}s",
            execution_log=f"Timeout after {timeout}s"
        )
    except Exception as e:
        return SimulationResult(
            is_success=False,
            conductivity=0.0,
            error_message=f"Subprocess error: {str(e)}",
            execution_log=str(e)
        )
    
    # output is now captured from subprocess.run result.stdout
    
    # Expected format: "Conductivity: 1.23e-06 S/cm"
    import re
    match = re.search(r"Conductivity:\s*([\d\.eE\-\+]+)\s*S/cm", output)
    
    if match:
        try:
            cond = float(match.group(1))
            
            # Progress validation: check for unrealistic results
            # 1. Check simulation time (if present)
            time_match = re.search(r"Time[=:]\s*([\d\.]+)\s*ns", output)
            if time_match:
                sim_time = float(time_match.group(1))
                if sim_time < 0.01:  # Less than 0.01 ns = time not advancing
                    return SimulationResult(
                        is_success=False,
                        conductivity=0.0,
                        error_message=f"Simulation time not advancing (only {sim_time:.4f} ns). Likely unrealistic barrier values.",
                        execution_log=output
                    )
            
            # 2. Check for unrealistic conductivity (too high = numerical error)
            if cond > 1e3:  # > 1000 S/cm is unrealistic for solid electrolytes
                return SimulationResult(
                    is_success=False,
                    conductivity=0.0,
                    error_message=f"Unrealistic conductivity: {cond:.2e} S/cm (too high, likely numerical error)",
                    execution_log=output
                )
            
            return SimulationResult(
                is_success=True,
                conductivity=cond,
                error_message=None,
                execution_log=output
            )
        except ValueError:
            return SimulationResult(
                is_success=False,
                conductivity=0.0,
                error_message=f"Failed to parse conductivity value from: {match.group(0)}",
                execution_log=output
            )
    else:
        return SimulationResult(
            is_success=False,
            conductivity=0.0,
            error_message=f"Output did not contain 'Conductivity: ... S/cm'. Output:\n{output}",
            execution_log=output
        )


def _simulator_node(state: AgentState):
    """
    Simulator Node
    """
    print(f"\n🚀 Simulator Starting...")
    
    code = state.get("current_code")
    if not code:
        return {
            "simulation_output": SimulationResult(
                is_success=False,
                conductivity=0.0,
                error_message="No code found in state",
                execution_log="No code provided"
            )
        }
    
    # Save code to file
    import os
    run_dir = state.get("run_dir")
    iteration = state.get("iteration_count", 0)
    code_path = ""  # Initialize to avoid NameError
    
    if run_dir:
        sim_dir = os.path.join(run_dir, "simulation")
        os.makedirs(sim_dir, exist_ok=True)
        code_path = os.path.join(sim_dir, f"final_state.py")
        
        try:
            with open(code_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"   💾 Saved code to: {code_path}")
        except Exception as e:
            print(f"   [Warning] Failed to save code: {e}")

        # Copy LLZO.cif if exists
        import shutil
        cif_src = os.path.join(Config.INITIAL_STATE_DIR, "LLZO.cif")
        cif_dst = os.path.join(sim_dir, "LLZO.cif")
        if os.path.exists(cif_src):
            try:
                shutil.copy(cif_src, cif_dst)
                print(f"   📄 Copied LLZO.cif to: {cif_dst}")
            except Exception as e:
                print(f"   [Warning] Failed to copy LLZO.cif: {e}")
        else:
             print(f"   [Warning] LLZO.cif not found at: {cif_src}")

    # Execute with file_path for __file__ resolution
    result = execute_simulation(code, file_path=code_path if run_dir else "", timeout=Config.TIMEOUT)

    
    # Display result in table format
    import math
    target = Config.TARGET_CONDUCTIVITY
    target_log = math.log10(target)
    initial = Config.INITIAL_CONDUCTIVITY
    initial_log = math.log10(initial)
    initial_error = initial_log - target_log  # Signed: + = overestimate
    
    w_state, w_sigma, w_log, w_error = 10, 18, 18, 18
    header_fmt = f"| {{:^{w_state}}} | {{:^{w_sigma}}} | {{:^{w_log}}} | {{:^{w_error}}} |"
    row_fmt    = f"| {{:^{w_state}}} | {{:^{w_sigma}}} | {{:^{w_log}}} | {{:^{w_error}}} |"
    sep = "+" + "-"*(w_state+2) + "+" + "-"*(w_sigma+2) + "+" + "-"*(w_log+2) + "+" + "-"*(w_error+2) + "+"
    
    print("\n" + sep)
    print(header_fmt.format("State", "σ_ion [S/cm]", "log(σ_ion)", "error (±)"))
    print(sep)
    print(row_fmt.format("Target", f"{target:.5e}", f"{target_log:.8f}", "-"))
    print(row_fmt.format("Initial", f"{initial:.5e}", f"{initial_log:.8f}", f"{initial_error:+.8f}"))
    
    if result.is_success and result.conductivity > 0:
        result_log = math.log10(result.conductivity)
        log_error = result_log - target_log  # Signed: + = overestimate
        print(row_fmt.format("Final", f"{result.conductivity:.5e}", f"{result_log:.8f}", f"{log_error:+.8f}"))
    else:
        print(row_fmt.format("Final", "FAIL", "FAIL", "FAIL"))
    
    print(sep)

    # No log error update here, archivist handles it
    
    return {"simulation_output": result}


def create_simulator_node():
    return _simulator_node
